version: '3.7'

services:
  web:
    image: node:12
    depends_on:
      - mongo_db
    container_name: nodejs
    volumes:
      - "./:/mydata/"
    ports:
      - '3001:3000'
    restart: always
    tty: true
    environment:
      MY_MONGO_HOST: mongo_db
      MY_MONGO_PORT: 27017
      MY_MONGO_DB_NAME: myapp
#      MY_MONGO_USER: user
#      MY_MONGO_PASS: pass

  mongo_db:
    image: mongo
    restart: always
    container_name: node_mongo_db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27100:27017
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

  mongo-express:
    depends_on:
      - mongo_db
    image: mongo-express
    container_name: node_mongo_ex
    restart: always
    ports:
      - 9000:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
volumes:
  mongo_data:
  mongo_config:

