version: '3.7'

services:
  web:
    image: node:12
    depends_on:
      - mongo_db
      - session_store
    container_name: nodejs
    volumes:
      - "./:/mydata/"
    ports:
      - '3001:3000'
    restart: always
    tty: true
    environment:
      MY_MONGO_HOST: mongo_db
      MY_MONGO_PORT: 27017
      MY_MONGO_DB_NAME: myapp
#      MY_MONGO_USER: user
#      MY_MONGO_PASS: pass
      MY_SESSION_STORE: "redis"  # "redis","mongo","memory"から選択可能。省略はmemoryになる
      MY_REDIS_HOST: session_store
      MY_REDIS_PORT: 6379

  mongo_db:
    image: mongo:4.2
    restart: always
    container_name: node_mongo_db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27100:27017
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

  mongo-express:
    depends_on:
      - mongo_db
    image: mongo-express
    container_name: node_mongo_ex
    restart: always
    ports:
      - 9000:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017

  session_store:
    image: redis:5.0
    restart: always
    container_name: redis_store
    ports:
      - 6391:6379
    volumes:
      - "session_data:/data"

  redis_commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - session_store
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:session_store:6379
    ports:
      - "9002:8081"

volumes:
  mongo_data:
  mongo_config:
  session_data:

